/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import static java.lang.Math.abs;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author yasiru
 */
public class LoginForm extends javax.swing.JFrame {
    long keyPressTime, keyReleaseTime, pressDiff, previousKeyReleaseTime, transferDifference;
    String key, previousKey;
    HashMap keyPressMap, transferDurationMap, userKeyPressMap, userTransferDurationMap;
    int count, keyDurations_sum, transferDurations_sum;
    boolean canRelease;
    
    LoginForm(HashMap userKeyDurations, HashMap userTransferDurations) {
        initComponents();
        this.userKeyPressMap = userKeyDurations;
        this.userTransferDurationMap = userTransferDurations;
        keyPressMap = new HashMap();
        transferDurationMap = new HashMap();
        keyReleaseTime = 0;
        count=0;
        keyDurations_sum = 0;
        transferDurations_sum = 0;
        givenText.setText("hello this is a keystroke authentication system. this is one method of bio authentication.");
        givenText.setEditable(false);
        userText.requestFocus();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        givenText = new javax.swing.JTextArea();
        cancelBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 1, 18))); // NOI18N

        userText.setColumns(20);
        userText.setRows(5);
        userText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userTextKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(userText);

        givenText.setColumns(20);
        givenText.setRows(5);
        jScrollPane2.setViewportView(givenText);

        cancelBtn.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(0, 153, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });

        loginBtn.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 153, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter the following text in the given text-box in lower case format ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void userTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextKeyPressed
        try{    
            if(givenText.getText().charAt(count)==evt.getKeyChar()){
                canRelease = true;
                key = Character.toString(evt.getKeyChar())+(count++);
                keyPressTime = System.currentTimeMillis();
                previousKeyReleaseTime = keyReleaseTime;
                transferDifference = keyPressTime - previousKeyReleaseTime;
                if(previousKey != null){
                    transferDurationMap.put(previousKey+"-"+key, transferDifference);
                }
            }
        }catch(IndexOutOfBoundsException exception){
            
        }
    }//GEN-LAST:event_userTextKeyPressed

    private void userTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextKeyReleased
        if(canRelease){
            canRelease = false;
            keyReleaseTime = System.currentTimeMillis();
            previousKey = key;
            pressDiff=keyReleaseTime-keyPressTime;
            keyPressMap.put(key, pressDiff);

        }
        
        
    }//GEN-LAST:event_userTextKeyReleased

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        if(givenText.getText().equals(userText.getText())){
            Set userset = userKeyPressMap.entrySet();
            Iterator user_i = userset.iterator();
            Set set=keyPressMap.entrySet();
            Iterator i=set.iterator();
            long key_diff = 0;
            while(user_i.hasNext() & i.hasNext()) {
               Map.Entry user_me = (Map.Entry)user_i.next();
               Map.Entry me = (Map.Entry) i.next();
               key_diff = abs((long)user_me.getValue()-(long)me.getValue());
               keyDurations_sum += key_diff;
            }
            float keyDurationsAvg = (float)keyDurations_sum/count;
            userset = userTransferDurationMap.entrySet();
            user_i = userset.iterator();
            set = transferDurationMap.entrySet();
            i = set.iterator();
            long transfer_diff = 0;
            while(user_i.hasNext() & i.hasNext()) {
               Map.Entry user_me = (Map.Entry)user_i.next();
               Map.Entry me = (Map.Entry)i.next();
               transfer_diff = abs((long)user_me.getValue()-(long)me.getValue());
               transferDurations_sum += transfer_diff;
            }
            float transferDurationsAvg = (float)transferDurations_sum/(count-1);
            if(keyDurationsAvg<30 & transferDurationsAvg<160){
                JOptionPane.showMessageDialog(null, "Login Successful!");
                new Home(userKeyPressMap, userTransferDurationMap).setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Login Failed!", "Error", JOptionPane.ERROR_MESSAGE);
                new Home(userKeyPressMap, userTransferDurationMap).setVisible(true);
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Texts mismatched. Try again.");
            new LoginForm(userKeyPressMap, userTransferDurationMap).setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextArea givenText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextArea userText;
    // End of variables declaration//GEN-END:variables
}
